# Generated by Django 5.0.2 on 2024-02-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время старта')),
                ('quantity_min', models.IntegerField(verbose_name='Минимальное количество студентов')),
                ('quantity_max', models.IntegerField(verbose_name='Максимальное количество студентов')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название урока')),
                ('link', models.URLField(verbose_name='Ссылка на видео')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Группа')),
                ('student', models.CharField(max_length=150, verbose_name='Ученик')),
                ('pay', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['id'],
            },
        ),
    ]
