# Generated by Django 5.0.2 on 2024-02-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_users_remove_group_student_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pay',
        ),
        migrations.AddField(
            model_name='users',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
